description "MANGO Node: serial acquisition of sensor readings"

start on runlevel [2345]
stop on runlevel [016]

respawn
respawn limit 10 5

script
    set -a
    test -f /opt/mango_node/.env && . /opt/mango_node/.env
    cd /opt
    exec /usr/bin/python3 -m mango_node.serial_acquire
end script

console log
