description "MANGO Node: Huawei E3372H-153 modem watchdog"

start on (runlevel [2345] and net-device-up IFACE!=lo)
stop on runlevel [016]

respawn
respawn limit 10 5

script
    set -a
    export PYTHONIOENCODING=utf-8
    export LANG=C.UTF-8
    test -f /opt/mango_node/.env && . /opt/mango_node/.env
    cd /opt
    exec /usr/bin/python3 -m mango_node.modem_monitor
end script

console log
