apiVersion: 1

datasources:
  - name: MANGO PostgreSQL
    type: postgres
    uid: mango-postgres
    url: db:5432
    database: ${DB_NAME}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
