[env:esp32dev]
platform = platformio/espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    sparkfun/SparkFun BNO080 Cortex Based IMU
    madhephaestus/ESP32Servo

build_flags =
    -DCORE_DEBUG_LEVEL=0
