"""Secure temporary download links for project documents.

POST /api/v1/docs/link
  Auth: any logged-in user
  Body: { "path": "/docs/file.pdf" }
  Returns: { "url": "/api/v1/docs/download/<token>", "expires_at": ISO, "filename": str }

GET /api/v1/docs/download/<token>
  No session required — token is the credential.
  Validates HMAC + expiry, logs the download, redirects to the static file.

GET /api/v1/admin/docs/activity  (admin only)
  Returns the last 200 download log entries.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import os
import time
from datetime import datetime, timezone, timedelta

from flask import Blueprint, current_app, jsonify, redirect, request, session

from app.extensions import db
from app.middleware.admin_required import login_required, admin_required
from app.models.download_log import DownloadLog

log = logging.getLogger("mango.docs_download")

docs_download_bp = Blueprint("docs_download", __name__, url_prefix="/api/v1")

_TOKEN_TTL = 15 * 60  # 15 minutes

# Only allow paths that start with one of these prefixes.
_ALLOWED_PREFIXES = ("/docs/", "/uploads/docs/")


# ── Token helpers ────────────────────────────────────────────────────────────

def _secret() -> bytes:
    return current_app.config.get("SECRET_KEY", "change-me").encode()


def _make_token(path: str) -> tuple[str, int]:
    expiry = int(time.time()) + _TOKEN_TTL
    payload = f"{path}|{expiry}"
    sig = hmac.new(_secret(), payload.encode(), hashlib.sha256).hexdigest()
    raw = json.dumps({"p": path, "e": expiry, "s": sig}, separators=(",", ":"))
    token = base64.urlsafe_b64encode(raw.encode()).decode().rstrip("=")
    return token, expiry


def _verify_token(token: str) -> str | None:
    """Returns the path if valid, else None."""
    try:
        padded = token + "=" * (-len(token) % 4)
        raw = base64.urlsafe_b64decode(padded).decode()
        data = json.loads(raw)
        path: str = data["p"]
        expiry: int = data["e"]
        sig: str = data["s"]
    except Exception:
        return None

    if time.time() > expiry:
        return None

    expected = hmac.new(_secret(), f"{path}|{expiry}".encode(), hashlib.sha256).hexdigest()
    if not hmac.compare_digest(sig, expected):
        return None

    return path


# ── Routes ───────────────────────────────────────────────────────────────────

@docs_download_bp.post("/docs/link")
@login_required
def request_link():
    body = request.get_json(silent=True) or {}
    path: str = (body.get("path") or "").strip()

    if not path:
        return jsonify({"error": "Campo 'path' requerido"}), 400

    if not any(path.startswith(p) for p in _ALLOWED_PREFIXES):
        return jsonify({"error": "Ruta no permitida"}), 400

    # Reject obvious traversal attempts
    if ".." in path or "\x00" in path:
        return jsonify({"error": "Ruta inválida"}), 400

    token, expiry = _make_token(path)
    filename = os.path.basename(path)
    expires_at = datetime.fromtimestamp(expiry, tz=timezone.utc).isoformat()

    log.info("doc link generated by user=%s for path=%s", session.get("user_id"), path)

    return jsonify({
        "url":        f"/api/v1/docs/download/{token}",
        "expires_at": expires_at,
        "filename":   filename,
        "ttl_minutes": _TOKEN_TTL // 60,
    }), 200


@docs_download_bp.get("/docs/download/<token>")
def download_file(token: str):
    path = _verify_token(token)
    if path is None:
        return jsonify({"error": "Enlace inválido o expirado"}), 410

    filename = os.path.basename(path)
    ip = request.headers.get("X-Forwarded-For", request.remote_addr or "").split(",")[0].strip()
    ua = (request.user_agent.string or "")[:512]

    try:
        entry = DownloadLog(
            path=path,
            filename=filename,
            user_id=session.get("user_id"),
            ip=ip,
            user_agent=ua,
        )
        db.session.add(entry)
        db.session.commit()
    except Exception:
        log.exception("failed to write download log")
        db.session.rollback()

    log.info("doc downloaded: path=%s ip=%s user=%s", path, ip, session.get("user_id"))

    # Redirect to the static file served by nginx
    base_url = current_app.config.get("PUBLIC_BASE_URL", "").rstrip("/")
    return redirect(f"{base_url}{path}", code=302)


@docs_download_bp.get("/admin/docs/activity")
@admin_required
def download_activity():
    rows = (
        DownloadLog.query
        .order_by(DownloadLog.downloaded_at.desc())
        .limit(200)
        .all()
    )
    return jsonify([r.to_dict() for r in rows]), 200
