[env:mango_motion]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

; WiFi + WebServer vienen incluidas en el framework ESP32-Arduino.
; No necesitan lib_deps extra.
lib_deps =
  ESP32Servo
  sparkfun/SparkFun BNO080 Cortex Based IMU @ ^1.1.9

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -O2
  ; Aumenta el stack de la tarea WiFi para el WebServer embebido
  -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
